title: Lemurenh√∂hle
views:
  - !include /config/lovelace/lovelace-home.yaml
  - !include /config/lovelace/lovelace-netatmo.yaml
  - !include /config/lovelace/lovelace-automation.yaml
  - !include /config/lovelace/lovelace-media.yaml
  - !include /config/lovelace/lovelace-plants.yaml
