- alias: Licht an 45min vor Sonnenuntergang
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
    - service: light.turn_on
      entity_id: group.licht_philips
      data:
        brightness: 200
        color_name: sandybrown

- alias: Licht aus 90min nach Sonnenaufgang
  trigger:
  - event: sunrise
    offset: 01:30:00
    platform: sun
  condition: []
  action:
  - service: light.turn_off
    entity_id: group.licht_philips

- alias: Unter der Woche, morgens Licht an
  trigger:
    platform: time
    at: '05:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      entity_id: group.licht_philips 
      data:
        brightness: 255
        color_name: lightcyan

- alias: Push Nachricht wenn Hochbeet 체ber 20 Grad
  trigger:
    platform: numeric_state
    entity_id: sensor.hochbeet_temperature_max_last_12h
    above: 20
  action:
    - service: notify.pushover_notification
      data:
        title: "Hochbeet sehr warm!"
        message: |
          Balkon:
          - {{ states.sensor.netatmo_outdoor_temperature.state }} 째C
          Hochbeet:
          - {{ states.sensor.hochbeet_temperature.state }} 째C ({{ states.sensor.hochbeet_temperature_max_last_12h.state }} 째C max/12h)
          - {{ states.sensor.hochbeet_moisture.state }} % Feuchtigkeit ({{ states.sensor.hochbeet_moisture_min_last_12h.state }} % min/12h)
          - {{ states.sensor.hochbeet_light_intensity.state }} lx
        data:
          sound: pianobar
          priority: 0
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.automation.push_nachricht_wenn_hochbeet_uber_20_grad.attributes.last_triggered | default(0)) | int > 14400)}}'
