homeassistant:
  name: !secret ha_instance_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 415
  unit_system: metric
  time_zone: Europe/Zurich
  customize: !include customize.yaml

lovelace:
  mode: yaml

default_config:

sensor:
  - platform: yr

tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://ha:3218
    
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

media_player:
  - platform: yamaha
    host: 192.168.3.150
    source_names:
      HDMI1: "TV"
      HDMI2: "SWITCH"
      HDMI3: "PS3"
      HDMI4: "CHROMECAS"
      HDMI5: "HDMI5"
      AV1: "Sonos"
      AV4: "HDMI ARC"
      AV5: "BLUETOOTH"
      AUX: "Phono"

influxdb:
  host: !secret influxdb_host
  port: 8086
  database: ha
  default_measurement: state

notify:
  - name: pushover_notification
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

device_tracker:
  - platform: bluetooth_tracker
  - platform: nmap_tracker
    hosts:
    - 192.168.3.246
    - 192.168.3.127
    track_new_devices: no
    interval_seconds: 30
    consider_home: 7

person: !include people.yaml

switch:
  - platform: mystrom
    host: 192.168.3.142
    name: Strom TV Rack
  - platform: mystrom
    host: 192.168.3.233
    name: Strom BÃ¼ro Server

sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:65:DC'
    name: Hochbeet
    force_update: true
    scan_interval: 600
    median: 3